version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cars
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    environment:
      STANDALONE: 'true'
    ports:
      - '6379:6379'

  cars:
    image: golang:latest
    env_file:
      - ./.env
    restart: always
    command: './wait-for -t 30 postgres:5432 -- /bin/app'
    ports:
      - '8080:8080'
volumes:
  data: {}