version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cars
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    environment:
      STANDALONE: 'true'
    ports:
      - '6379:6379'

  cars:
    image: golang:latest
    env_file:
      - ./.env
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    command: './entrypoint.sh'
    depends_on:
      - postgres
      - redis
volumes:
  data: {}